### ISSUE TITLE
Wrong Definitions of xlim() and ylim() Parameters

### ISSUE THREAD

**Issue by amangoel185** [piccolomo/plotext#112]
Hi @piccolomo,

Thank you for your amazing work on plotext! 

I wanted to define `ylim()` for plots in uproot-browser (scikit-hep/uproot-browser#70) and got confused with how `xlim()` and `ylim()` are defined. The [Plot Limits](https://github.com/piccolomo/plotext/blob/d3f181311dcc4abe66662d70dc833fc471fef05f/readme/settings.md?plain=1#L19) documentation mentions how `xlim(left, right)` and `ylim(lower, upper)` work, which is intuitive. However, [`_core.py`](https://github.com/piccolomo/plotext/blob/d3f181311dcc4abe66662d70dc833fc471fef05f/plotext/_core.py#L58) and [`_figure.py`](https://github.com/piccolomo/plotext/blob/d3f181311dcc4abe66662d70dc833fc471fef05f/plotext/_figure.py#L124) define `xlim()` with `lower` and `upper`, and vice versa for `ylim()`. The same reversal can be observed at various other places such as [`_monitor.py`](https://github.com/piccolomo/plotext/blob/d3f181311dcc4abe66662d70dc833fc471fef05f/plotext/_monitor.py#L51) and [`doc.py`](https://github.com/piccolomo/plotext/blob/d3f181311dcc4abe66662d70dc833fc471fef05f/plotext/_utility/doc.py#L49) (for `xside` too here).

I believe `xlim()` should use `left` and `right` while `ylim()` should use `upper` and `lower`. Is this by design or have the definitions been reversed everywhere?

**Comment by piccolomo** [comment]
Hi @amangoel185, thanks a lot for taking the time to drop this very important issue. What you report is a total blunder on my side, which I will eventually correct. Please report any other, even here, if you spot them.

Thanks
Savino

**Comment by amangoel185** [comment]
I could open a PR for the same if you'd like.

Also, @henryiii suggested it might be better for `ylim()` to use `bottom` and `top` instead, so that it falls in line with [matplotlib](https://github.com/matplotlib/matplotlib/blob/4f5cacfde9024076d9ab0cb6ad1c9a7cf352d5f9/lib/matplotlib/axes/_base.py#L3948) too!

**Comment by piccolomo** [comment]
Cool, if you need it urgently, feel free to open a PR, otherwise work on it but it is going to take some time as issues are piling up and I am not dealing with `plotext` recently. I will deal with oldest first I guess.

**Comment by piccolomo** [comment]
Hi @amangoel185 , I finally updated `plotext` and the new version should solve this issue. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Any feedback is welcomed. Please report if the issue persists. 

Thanks a lot for your inputs and all the best,
Savino

**Comment by matthewfeickert** [comment]
:wave: @piccolomo Thanks very much for addressing this Issue. Just to double check, as the [GitHub commit history](https://github.com/piccolomo/plotext/commits/master) isn't super clear/is perhaps altered to only show releases, the version that this fix landed in was [`plotext` `v5.2.2`](https://pypi.org/project/plotext/5.2.2/#history), correct? I'm going by release dates on PyPI, as this Issue was closed on 2022-09-02 and `v5.2.2` landed the same day.

**Comment by piccolomo** [comment]
Hi @matthewfeickert, apologies to everyone, the commit history has been restored starting from all working past version I could retrieve and putting the package back up again. I now know the fundamentals of git (which I did not before, causing problems to the git projects) and the history should be clearer from there on. 

I double checked as well,  and `v5.2.2` is the version from which the problem was solved. From there one, all more updated version should have this issue solved.
