### ISSUE TITLE
Conditional rendering

### ISSUE THREAD

**Issue by darul75** [piccolomo/plotext#132]
Hello @piccolomo 

Hope you do not mind me asking a lot of questions.

This one is on how to put a conditional rendering in the python code.

I can not find the proper syntax for it.

`if len(myArray) > 0 : plt.stacked_bar(....); \`

I have tried different syntax but can not figure out the best way to add a single if statement to control the rendering of a chart.

If you could help.

Thanks a lot.

**Comment by darul75** [comment]
Ok, managed to get it working using this bash trick

```
read -r -d '' pythonScript <<- EOM
import plotext as plt

pizzas = ["Sausage", "Pepperoni", "Mushrooms", "Cheese", "Chicken", "Beef"]
percentages = [14, 36, 11, 8, 7, 4]

plt.bar(pizzas, percentages)
plt.title("Most Favored Pizzas in the World")
plt.show()
EOM
```

it does the job and I can type normal python, no more `;` and just using indentation.

**Comment by piccolomo** [comment]
Hi @darul75,

thanks for posting again and glad you found a solution. Unfortunately this issue is not directly about `plotext`, and I will delete it.

I recommend using [stackoverflow.com](stackoverflow.com) or related for this kinds of issues.

In general, any issue report or feature request directly about `plotext` is more then welcomed.

Thanks and all the best, 
Savino
