### ISSUE TITLE
Join Time Gaps on CandleStick

### ISSUE THREAD

**Issue by ineteye** [piccolomo/plotext#138]
Hi!
1.Is it possible to join such weekends time gaps?

![image](https://user-images.githubusercontent.com/32996306/194184158-8209c869-4efb-437c-9245-4a5a343d7b7e.png)

2.Is there any way to add margin or offset from plot sides?

![image](https://user-images.githubusercontent.com/32996306/194185143-ca7b8f65-ff5a-41bc-8fde-13251147306f.png)

3. Ability to print OHLC bars will be also awesome

![image](https://user-images.githubusercontent.com/32996306/194185397-9a74e698-4ad7-4e7b-96db-953300802d90.png)

THANKS!!!!

**Comment by piccolomo** [comment]
1. I don't think it is. 2. Using xlim() and ylim(). 3. I don't think there exists the proper markers for those

**Comment by ineteye** [comment]
Sorry can not make xlim to work, plot was based on this example code:

```
import yfinance as yf
import plotext as plt

plt.date_form('d/m/Y')
start = plt.string_to_datetime('11/04/2022')
end = plt.today_datetime()
data = yf.download('goog', start, end)

dates = plt.datetimes_to_string(data.index)

plt.xlim(-1)

plt.candlestick(dates, data)
plt.show()
```

* i was trying to use like :
       plt.xlim(-1),plt.xlim(-80)  -- works but not how expected
       plt.xlim(-1,1) ,plt.xlim(-1,2) ..... ---- always get list index out of range
* len(dates)= 83

Can you please help, i want add padding 1 bar from left and right

**Comment by ineteye** [comment]
Thanks!!! Will wait while it will be available on upgrade :)

Right now still 5.2.7
![image](https://user-images.githubusercontent.com/32996306/194328072-76d18e07-c95a-4d0f-8572-dc6d26645b7c.png)

**Comment by ineteye** [comment]
Thanks again! Now works fine :)))

**Comment by ineteye** [comment]
Sorry for bothering again but can not figure out how to swap yticks to right side on candlestick
It always on left i tryed:
```
plt.yreverse(True,yside=2) 
plt.yreverse(True,yside=1) 
plt.yticks(df['Close'],yside=2) 
plt.yticks(df['Close'],yside=1)
```
And it still on the left...
![image](https://user-images.githubusercontent.com/32996306/194346575-c1268cd1-36b4-4e89-8d7b-5e5025a66123.png)

**Comment by piccolomo** [comment]
Interesting bug, the function `candlestick()` lacks the parameters `xside` and `yside` to achieve this, as in all other main plots. I will work on this and update.

**Comment by piccolomo** [comment]
Btw, now also the x axis could be change (I did not double check tough).

**Comment by ineteye** [comment]
hline and text creating second yticks,do not know bug that or not ;)))

```
plt.hline(100,'red')
plt.text('100',x=dates[-1],y=100)
```

![image](https://user-images.githubusercontent.com/32996306/194357346-7cbc6d49-b238-4b48-9c8a-11fe7f95f86c.png)

If use with yside=2, no double bar:
```
plt.hline(100,'red',yside=2)
plt.text('100',x=dates[-5],y=100,color='red',yside=2)
```

**Comment by piccolomo** [comment]
That is not a bug, because in the first case the text or line is added to left y axis and so its ticks are shown as well. In the second case, the left y axis is never used and so no ticks are shown. Thanks tough.

**Comment by piccolomo** [comment]
Hi I have updated the title and removed the "Join WeekEnd Time Gaps and OHLC Plot". If you want to keep the OHLC Plot part, would be great if you could open an issue titled: "Feature Request: OHLC Plot" or similar. 
Thanks
P.S: I am out of `plotext` for awhile, but will start coding eventually.

**Comment by piccolomo** [comment]
Hi @ineteye, I have cleaned this issue and moved sub requests to other issues for clarity in case some other users need to find it.

Thanks for reporting and for any other report is very welcomed! :-) 
Savino

**Comment by piccolomo** [comment]
Hi @ineteye,

  coming back to this old thread, with apologies for the delay.

  Both halves of it are settled in [plotext](https://plotext.readthedocs.io/en/latest/) 6.

  The **limits** are now set on the axis itself, with [ruler("x").lim()](https://plotext.readthedocs.io/en/latest/ruler.html#limits) instead of `xlim()`, and they take date strings once the [date axis](https://plotext.readthedocs.io/en/latest/date.html) is switched on, so a margin on either side is a matter
  of asking for a wider range:

  ```python
  fig.date("x").activate()
  fig.draw(fig.candlestick(stock))
  fig.ruler("x").lim("25/12/2025", "25/01/2026")
  ```

  The **OHLC bars** you asked for in this same thread, moved to [Issue 149](https://github.com/piccolomo/plotext/issues/149), are drawn by `candlestick(style = "ohlc")`; see that issue for the picture and the code.

  I have also added you to the [credits](https://plotext.readthedocs.io/en/latest/credits.html) of the documentation, for that idea.

  plotext 6 is out as a beta:
  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks again for the reports,
  Savino
