### ISSUE TITLE
Plotting without ANSI escapes?

### ISSUE THREAD

**Issue by machineroom** [piccolomo/plotext#162]
Hi, love this library! For my use case sometimes logs get exported as plan text which of course loses the ANSI chars and formatting is messed up. Is it possible to plot to plain text? Appreciate this might lose some of the nice features.

**Comment by piccolomo** [comment]
Hi @machineroom, not sure if I understand correctly, but if I do, you may want to try these methods:

- `clear_colors()`, to remove colors before plotting, explained [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#clearing-functions). 
- `build()`, explained [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#canvas-utilities),
- and `save_fig()`, explained [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#canvas-utilities).

All previous functions have their own methods as well. I hope it helps, but let me know if it does not. 
All the best,
Savino.

**Comment by machineroom** [comment]
Thanks :) clc() does exactly what I want and works well to include the plots in plain text logging.

**Comment by piccolomo** [comment]
Cool!

**Comment by piccolomo** [comment]
Hi @machineroom, and sorry for coming back to this so late.

  Since you asked, version 6 of [plotext](https://plotext.readthedocs.io/en/latest/) offers four ways to get a plot with no colors, where version 5 had [`clc()`](https://github.com/piccolomo/plotext/blob/5.3.2/readme/utilities.md#clearing-functions):

  ```python
  import plotext as plt

  fig = plt.figure
  fig.draw(fig.signal(plt.sin()).lines().label("wave"))
  fig.title("Plain Text Plot")
  plot = fig.build()

  plot.print(colorless = True)              # 1. printed with no color codes at all
  text = plot.string(colorless = True)      # 2. the same as a plain string, for your logs
  plot.save("plot.txt")                     # 3. written to file, colorless by its extension
  text = plt.uncolorize(plot.string())      # 4. the colors stripped from a string you already have
  ```

  and a fifth, if you would rather the plot itself carried no colors from the start:

  ```python
  fig.theme("colorless")                    # every element drawn in the terminal's own color
  ```

  The first four leave **no escape codes whatsoever**; the theme leaves only the reset one, so a log holds the drawing and nothing else.

  Where each lives: `print()`, `string()` and `save()` on the [matrix](https://plotext.readthedocs.io/en/latest/matrix.html) page, [`uncolorize()`](https://plotext.readthedocs.io/en/latest/colorize.html) with the colored strings, and the themes on the
  [theme](https://plotext.readthedocs.io/en/latest/theme.html) page. The [clearing](https://plotext.readthedocs.io/en/latest/clear.html) methods are a different matter: they reset a plot to its defaults, colors included, rather than removing them.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks for the kind words about terminals,

  Regards,
  Savino
