### ISSUE TITLE
Add parameter in read_data() method to skip first N rows

### ISSUE THREAD

**Issue by cwaldbieser** [piccolomo/plotext#165]
All the CLI examples are basically of the form `python -m plotext ...` where you just are basically writing a python program on one line.
There aren't any examples using the CLI tool e.g. `plotext scatter ...`.

I'm not sure if I'm doing something wrong when I try to use it, but if I try to feed it a simple CSV file with x,y coordinates, it throws a `ValueError: Date Form should be: %d/%m/%Y`, presumably because it is trying to interpret the values as dates rather than plain old numbers?

scatter.csv
```
x,y
1,12
2,27
3,52
4,87
5,132
6,187
7,252
8,327
9,412
10,507
11,612
12,727
13,852
14,987
15,1132
16,1287
17,1452
18,1627
19,1812
20,2007
21,2212
```

My command:
```bash
plotext scatter -d ',' --path ./scatter.csv -xcol 1 -ycols 1
Traceback (most recent call last):
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_date.py", line 48, in string_to_time
    return dt.strptime(string, input_form).replace(tzinfo = tz.utc).timestamp() - time0
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'x' does not match format '%d/%m/%Y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waldbiec/.local/bin/plotext", line 8, in <module>
    sys.exit(main())
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/plotext_cli.py", line 326, in main
    plot(xc, Yc)
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/plotext_cli.py", line 259, in plot
    plt.scatter(x, y, marker = marker, color = None if type == 'plotter' else color) if type in ['scatter', 'plotter'] else None
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_core.py", line 176, in scatter
    _figure._active.scatter(*args, xside = xside, yside = yside, marker = marker, color = color, style = style, fillx = fillx, filly = filly, label = label)
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_figure.py", line 212, in scatter
    self._draw(*args, xside = xside, yside = yside, lines = False, marker = marker, color = color, style = style, fillx = fillx, filly = filly, label = label)
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_figure.py", line 209, in _draw
    self.monitor.draw(*args, **kwargs) if self._no_plots else [[self._get_subplot(row, col)._draw(*args, **kwargs) for col in self._Cols] for row in self._Rows]
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_monitor.py", line 288, in draw
    self.add_data(*args)
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_monitor.py", line 311, in add_data
    x, x_date = self.to_time(x)
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_monitor.py", line 365, in to_time
    data = self.date.strings_to_time(data) if dates else data
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_date.py", line 53, in strings_to_time
    return [self.string_to_time(el, input_form) for el in strings]
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_date.py", line 53, in <listcomp>
    return [self.string_to_time(el, input_form) for el in strings]
  File "/home/waldbiec/.local/pipx/venvs/plotext/lib/python3.10/site-packages/plotext/_date.py", line 50, in string_to_time
    raise ValueError('Date Form should be: ' + input_form)
ValueError: Date Form should be: %d/%m/%Y
```

**Comment by cwaldbieser** [comment]
I think I figured out the problem I was having.

```bash
$ plotext scatter -d ',' --path <(tail -n 20 ./scatter.csv) -xcol 1 -ycols 2
```

If you can forgive the bash-ism, it seems that `plotext` doesn't like the fact that my CSV file had a header row.

**Comment by piccolomo** [comment]
I quickly reply but will come back to it: ye you spotted yourself the
issue, which still reminds me to add a header parameter to include or note
first row. Would that help?
Thanks for reporting,
- Savino

**Comment by piccolomo** [comment]
cool, may take some time tough, as I am busy. If you find a quick and easy fix for repo, a PR is welcomed! Otherwise I will deal with it eventually.

all the best

**Comment by cwaldbieser** [comment]
I made PR #166 to address this.

**Comment by piccolomo** [comment]
Hi @cwaldbieser,

sorry for such long break.

I have updated the packed, and called the very same parameter `first_row`: you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Here are the download instruction [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#install).

Thank you a lot for the help.
Savino

**Comment by cwaldbieser** [comment]
Thanks!

**Comment by piccolomo** [comment]
Hi @cwaldbieser, and sorry for coming back so long after the fact.

  Your request went in as `first_row` in version 5, and version 6 of [plotext](https://plotext.readthedocs.io/en/latest/) answers it differently, because reading a file and drawing a plot became separate things there.

  **In Python**, the reader hands you every row and skipping any number of them is a slice, which also leaves the header at hand for the axis names:

  ```python
  import plotext as plt

  rows = plt.file.csv("scatter.csv")        # every row, header included
  header, rows = rows[0], rows[1:]          # or rows[N:], skipping as many as you like

  x = [float(row[0]) for row in rows]
  y = [float(row[1]) for row in rows]

  fig = plt.figure
  fig.draw(fig.signal(x, y, marker = "hd").lines())
  fig.label(header[0], axis = "x")
  fig.label(header[1], axis = "y")
  fig.title("a csv with a header row")
  fig.show()
  ```

  **From the command line**, `@path:file.csv` passes the columns of a file straight to a method. Your question made me look at it again, and it was quietly dropping the first row of every file, which cost a data point to anyone whose file had no header. From the next build it reads every row instead, so a
  file carrying a header needs it taken off first:

  ```bash
  tail -n +2 scatter.csv | plotext --figure --signal - --draw --show
  ```

  while `@path:file.csv:dict` still uses that first row, as the keys of a dictionary, which is how the candlestick data is read.

  Two more things came out of the same look: a file ending with a new line used to lose **all** its columns, which is fixed, and the bundled sample table has had its header removed so that it reads plainly.

  The details are on the [file toolkit](https://plotext.readthedocs.io/en/latest/file.html) page and in the [reading files](https://plotext.readthedocs.io/en/latest/cli.html#reading-files) section of the command line page. You remain in the [credits](https://plotext.readthedocs.io/en/latest/credits.html) for
  the idea and the code.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks again, and sorry for the wait,

  Regards,
  Savino
