### ISSUE TITLE
Circular import error on plotext attributes

### ISSUE THREAD

**Issue by glebdovzhenko** [piccolomo/plotext#191]
Hello,

I've tried to install plotext and cannot import anything from it, I keep getting 
```Python
AttributeError: partially initialized module 'plotext' has no attribute 'show' (most likely due to a circular import)
```
for any attribute of plotext from the [Scatter plot example](https://github.com/piccolomo/plotext/blob/master/readme/basic.md#scatter-plot).

Here's my environment (Python 3.11.5):
```
anyio==4.0.0
bibtexparser @ git+https://github.com/sciunto-org/python-bibtexparser@770eb001349dcad48149bc101f07cfc88282d8b3
certifi==2023.7.22
h11==0.14.0
httpcore==0.18.0
httpx==0.25.0
idna==3.4
importlib-metadata==6.8.0
linkify-it-py==2.0.2
markdown-it-py==3.0.0
mdit-py-plugins==0.4.0
mdurl==0.1.2
plotext==5.2.8
py-cui==0.1.6
Pygments==2.16.1
pylatexenc==2.10
PyTermGUI==7.7.0
rich==13.6.0
simple-term-menu==1.6.1
sniffio==1.3.0
textual==0.40.0
typing_extensions==4.8.0
uc-micro-py==1.0.2
zipp==3.17.0
```

Thanks in advance.

**Comment by glebdovzhenko** [comment]
Sorry, that was my mistake. I named the file I ran `plotext.py`

**Comment by piccolomo** [comment]
No problem! Glad you find a way around it

**Comment by piccolomo** [comment]
Hi @glebdovzhenko, and sorry for the very late word on this.

  You found it yourself: the file you were running was named `plotext.py`, so Python imported it instead of the package. Nothing on our side, and version 6 of [plotext](https://plotext.readthedocs.io/en/latest/) behaves the same way, as would any package: the rule is simply never to name a script after the
  library it imports.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks for closing the loop on it,

  Regards,
  Savino
