### ISSUE TITLE
plotsize() doesn't resize plot when making terminal larger

### ISSUE THREAD

**Issue by nicrip** [piccolomo/plotext#23]
Hi - first of all, this terminal plotter is awesome! Thanks for the effort!

I noticed that with a single plot, the plot will only resize if the terminal is made smaller - if the terminal is made larger, the plot doesn't become larger with it.

I think the issue with your latest refactor is that you're missing a couple of lines in plotsize():

```
def plotsize(width = None, height = None):
    width, height = _ut.set_first_to_both(width, height)
    width, height = _ut.set_list_to_both(width, height)
    _fig.subplot.width = width
    _fig.subplot.height = height
```

there maybe should be the two additional lines below?

```
def plotsize(width = None, height = None):
    width, height = _ut.set_first_to_both(width, height)
    width, height = _ut.set_list_to_both(width, height)
    _fig.width = width
    _fig.height = height
    _fig.subplot.width = width
    _fig.subplot.height = height
```

**Comment by piccolomo** [comment]
Hi @nicrip ,

thanks a lot for the message and issue report. 

Indeed there was a bug, which was due to the fact that the plot size adapts to the terminal only if the values of `subplot.width` and `height` are None. Once the plot is done though, those value are fixed and the plot size no longer adapts. I modified the `plotsize()` function so that it now should work. 

(`_fig.width`  and  `_fig.height` fix the entire figure size including the optional subplots, but thanks for suggesting)

The new version of `plotext`  is available in [pypi](https://pypi.org/project/plotext/) and [github](https://github.com/piccolomo/plotext). 

I hope it fixed the problem, but in case the issue could be reopened.
