### ISSUE TITLE
0 in y-values in bar chart

### ISSUE THREAD

**Issue by jeppenodgaard** [piccolomo/plotext#30]
This works as expected (all x values are show even if the y-value is 0):
```
python3 -c "import plotext as plt; plt.bar([1,2,3],[1,0,1]); plt.show()"
```

If there is a 0 value at the beginning of the array it causes IndexError:
```
python3 -c "import plotext as plt; plt.bar([1,2,3],[0,1,1]); plt.show()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/plotext/plot.py", line 954, in bar
    _fig.subplot.point_color[-1] = _fig.subplot.point_color[-2]
IndexError: list index out of range
```

If there is a 0 value at the end of the array it is not shown in the bar chart:
```
python3 -c "import plotext as plt; plt.bar([1,2,3],[1,1,0]); plt.show()"
```

**Comment by piccolomo** [comment]
Good points. Holiday time... I will get back

**Comment by piccolomo** [comment]
Hi @jeppenodgaard,

thanks for message, you raised good points. 

As of now the bar plot doesn't show any bar if the bar value is 0 so:

- if 0 is on the right side, naturally it won't be shown.
- If 0 is on the left I suppose the error come from the fact that the first bar is not plotted and the second bar searched for the settings of the previous bar and cannot find it. 

not sure how to solve this actually, I guess I would have to either impose the x limits to cover the entire field or something more creative... any idea is welcomed. but for next version I will do my best to remove this bug.

For now thanks and till next time.

**Comment by joseanor** [comment]
@piccolomo  Is there a particular reason you are hard ignoring 0 based values?

https://github.com/piccolomo/plotext/blob/master/plotext/plot.py#L963

Removing this line of code resolves this reported issue. I see no ill side-effects from removing. Can push upstream at some point as well.

**Comment by piccolomo** [comment]
Hi @joseanor ,

I think the issue was that If I remove that line, a 0 bar will still appear as bar with single character height, and I preferred the bar not to be shown at all (like with `matplotlib`). 

I am in the process of rewriting the code (it is gonna take some time): Which solution would you prefer? Would it still be ok for the bar to be shown? I could think of another solution as well.

Thanks

**Comment by joseanor** [comment]
@piccolomo  I think it is better to have a small bar show up as opposed to breaking the rendering.

**Comment by clfriede** [comment]
@piccolomo I agree with Jordan.  A thin line is better than it crashing.  As a feature, it may be worth printing the value of the bar centered on the top of the bar.  For example if the bar had 1000, the top would be something like ------1000------.   Same would go for 0.  In that way, you could tell what the actual value was for the bar.

Thanks.

Cliff

**Comment by piccolomo** [comment]
Hi @jeppenodgaard, @joseanor  and @clfriede. 

the new 4.0.0 version of `plotext` is now available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/). :-)

This version should resolve this issue, but let us know otherwise.

Thanks and all the best,
Savino
