### ISSUE TITLE
Better error message for figure max row/col

### ISSUE THREAD

**Issue by soraxas** [piccolomo/plotext#60]
I was confused by a strange index out of bound error
```python
  File "xxxxx/terminal-plot/lib/python3.9/site-packages/plotext/_figure.py", line 55, in set_subplot
    self.subplot = self.subplots[self.row][self.col]
IndexError: list index out of range
```
which, after some extensive investigation I realise it's due to 
https://github.com/piccolomo/plotext/blob/db4bb95b1ac35e47684c6cb0bcf93d8916100fcd/plotext/_figure.py#L41

and the defaults is defined in 
https://github.com/piccolomo/plotext/blob/db4bb95b1ac35e47684c6cb0bcf93d8916100fcd/plotext/_default.py#L6

---------------

I don't oppose sane defaults (it should probably be configurable). However, this override is undetectable from user code as it is enforced in figure creation without any notice. In my opinion, it might be better off throw an exception instead of silently overrides the subplot size...

**Comment by piccolomo** [comment]
Hi @soraxas, thanks for the report and sorry for late reply (I put aside this project for awhile after latest version update).

I understand the issue: It seems it requires the creation of custom exceptions, which I am not familiar with yet, therefore I will work on it for next version. 

Also I like the idea of giving the user the ability to configure default values, something i will also think about. 

I will update and thanks

**Comment by piccolomo** [comment]
Hi @soraxas ,

thanks a lot for the issue report. I have sorted the issue in the newly updated 4.1.0 version, available on [github](https://github.com/piccolomo/plotext) and [pypi](https://pypi.org/project/plotext/).

Now setting a higher number of `rows` or `cols` should throw and exemption. 

Also in order to change the default value, it is probably easier to do it directly instead of creating a function. Here is how:

```
plt.figure.default.rows_max = 13
plt.figure.default.cols_max = 20
```
Please let me know what you think, especially if the issue persists in any other form. 

All the best,
Savino.

**Comment by soraxas** [comment]
Thanks for the kind reply and update on matter, appreciate it! Thanks for the amazing work
