### ISSUE TITLE
limit_size(False) causes Infinite Loop

### ISSUE THREAD

**Issue by saddy001** [piccolomo/plotext#71]
```python
import plotext as plt

# plt.plot_size(240, 30)
plt.limit_size(False, False)
plt.subplots(1, 2)

plt.subplot(1, 1)
l = 256
plt.plot(plt.sin(length=l), marker="fhd", color=list(range(l)))
plt.title("Plot Colors")
plt.canvas_color(254)
plt.axes_color((20, 40, 100))  # rgb coloring
plt.ticks_color("bright-yellow")

plt.subplot(1, 2)
l = 256
plt.plot(plt.sin(length=l), marker="fhd", color=list(range(l)))
plt.title("Plot Colors")
plt.canvas_color(254)
plt.axes_color((20, 40, 100))  # rgb coloring
plt.ticks_color("bright-yellow")

plt.show()
```

**Comment by piccolomo** [comment]
i didn't look at this properly, but as a start you could try to uncomment the line `# plt.plot_size(240, 30)`.

The `plt.limit_size(False, False)` line internally sets the plot size to an astronomical value (obviously larger then terminal size) and therefore it cannot be used alone. 

did it work?

**Comment by saddy001** [comment]
No, still infinite loop.

**Comment by piccolomo** [comment]
Hi @saddy001 ,

thanks again for the report. The solution was actually simpler: when the plot dimensions are set to basically infinity with `plt.limit_size(False, False)`, one needs to define the actual dimensions desired for each subplot (or at least the ones in the main diagonal in the matrix of subplots, so that the others get automatically set). Here is a simple example:
```python
import plotext as plt

plt.limit_size(False, False)
plt.subplots(1, 2)

l = 256
plt.subplot(1, 1)
plt.plot(plt.sin(length=l))
plt.plot_size(100, 10)

plt.subplot(1, 2)
plt.plot(plt.sin(length=l))
plt.clc()
plt.plot_size(50, 10)

plt.show()
```
which outputs:
![image](https://user-images.githubusercontent.com/56689657/152647337-d9e9384e-7b23-48c3-b125-d8660678294e.png)

Obviously you could set the dimensions now so that they go beyond the terminal ones. 

I have updated the package for other reasons to [version 4.1.7 ](https://github.com/piccolomo/plotext) (not yet available on PyPi) and it can be download the latest GitHub using: 
```console
pip install git+https://github.com/piccolomo/plotext
```
note: you need git installed to be able to run the latest command.

Could you kindly double check that the code woks for you as well?

Thanks,
Savino
